### ISSUE TITLE
Composer install Fails on First step : create-project appaydin/pd-admin pdadmin

### ISSUE THREAD

**Issue by yudhir** [rmznpydn/pd-admin#6]
Cannot determine controller argument for "Pd\WidgetBundle\Controller\WidgetController::configs()": the $cache argum
!!    ent is type-hinted with the non-existent class or interface: "Psr\SimpleCache\CacheInterface".

**Comment by cesurapp** [comment]
Symfony 4.3 update has been made. Could be a bug.

**Comment by appaydin** [comment]
The following package is missing, install it. `composer require symfony/cache`

**Comment by cesurapp** [comment]
Update packages. "composer update"
